name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout current mod
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache xmake installation only
      - name: Cache xmake
        uses: actions/cache@v3
        with:
          path: C:\ProgramData\chocolatey\lib\xmake
          key: xmake-${{ runner.os }}-v2.7.8
          restore-keys: |
            xmake-${{ runner.os }}-

      # Install xmake if not cached
      - name: Install xmake
        shell: powershell
        run: |
          if (!(Get-Command xmake -ErrorAction SilentlyContinue)) {
              choco install xmake -y
          } else {
              Write-Host "xmake already installed, skipping..."
          }

      # Clone AmethystAPI based on PR branch
      - name: Clone AmethystAPI based on PR
        shell: powershell
        run: |
          $pr_repo = "${{ github.event.pull_request.head.repo.clone_url }}"
          $pr_branch = "${{ github.event.pull_request.head.ref }}"

          Write-Host "Cloning Amethyst from PR branch $pr_branch at $pr_repo"

          try {
              git clone --depth 1 --recurse-submodules --branch $pr_branch $pr_repo Amethyst
          } catch {
              Write-Host "PR branch not found in Amethyst repo, falling back to main"
              git clone --depth 1 --recurse-submodules https://github.com/FrederoxDev/Amethyst.git Amethyst
          }

      # Configure with xmake
      - name: Configure with xmake
        shell: powershell
        run: |
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv
          xmake f -y --automated_build=y

      # Build with xmake
      - name: Build with xmake
        shell: powershell
        run: |
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv
          xmake