name: PR Build Check

on:
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: windows-latest
        steps:
            # Checkout current mod
            - name: Checkout code
              uses: actions/checkout@v4

            # Checkout AmethystAPI into /Amethyst
            - name: Clone AmethystAPI based on PR
              shell: powershell
              run: |
                # Determine the PR head repo and branch
                $pr_repo = "${{ github.event.pull_request.head.repo.clone_url }}"
                $pr_branch = "${{ github.event.pull_request.head.ref }}"

                Write-Host "Cloning Amethyst from PR branch $pr_branch at $pr_repo"

                # Attempt to clone the PR branch
                try {
                    git clone --recurse-submodules --branch $pr_branch $pr_repo Amethyst
                } catch {
                    Write-Host "PR branch not found in Amethyst repo, falling back to main"
                    git clone --recurse-submodules https://github.com/FrederoxDev/Amethyst.git Amethyst
                }

            # Build dependencies
            - name: Install Build Tools
              shell: powershell
              run: |
                choco install xmake -y

            - name: Build
              run: |
                Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
                refreshenv

                xmake f -y --automated_build=y
                xmake
              shell: powershell